on: [push, pull_request, workflow_dispatch]

#env:
#  MAVEN_VERSION: 3.9.11

jobs:
#  myjob1:
#    runs-on: docker
#    steps:
#      - run: "cat /etc/os-release" # Debian GNU/Linux 12 (bookworm)
#      - run: node --version # v22.21.1
#      - uses: actions/checkout@v6
#      - uses: actions/setup-java@v5
#        with:
#          distribution: 'temurin'
#          java-version: '25'
#          cache: 'maven'
#      - run: curl "https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" -s | tar -xz -C /usr/local
#      - run: ln -s -t /usr/local/bin/ /usr/local/apache-maven-$MAVEN_VERSION/bin/mvn
#      - run: mvn -B clean deploy
  ci-build:
    #needs: myjob1
    runs-on: docker
    container:
      image: code.phoswald.ch/philip/builder:latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: mkdir -p ~/.m2 &&  echo "${{ secrets.M2_SETTINGS }}" > ~/.m2/settings.xml
      - run: mvn -B clean deploy
