on: [push, pull_request]

env:
  MAVEN_VERSION: 3.9.11

jobs:
  myjob1:
    runs-on: docker
    # container:
    #   image: maven:3.9.11-eclipse-temurin-21-alpine      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: id && pwd && ls -la
      # - run: "cat /etc/os-release" # Debian 12 (/etc/lsb-release does not exist)
      # - run: "echo $PATH"
      - run: node --version # v22.21.1
      - run: java -version
      - run: curl "https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" -s | tar -xz -C /usr/local
      - run: ln -s -t /usr/local/bin/ /usr/local/apache-maven-$MAVEN_VERSION/bin/mvn
      - run: mvn -version
      - run: mvn -B clean verify 

  # myjob2:
  #   needs: myjob1
  #   runs-on: docker
  #   container:
  #     image: maven:3.9.11-eclipse-temurin-21-alpine      
  #   steps:
  #     - run: hostname && id && pwd && ls -la
